# Generated by Django 5.0 on 2024-01-11 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('v8yOf2', models.PositiveIntegerField(verbose_name='sector number')),
                ('MuEJnH', models.CharField(max_length=50, verbose_name='district name')),
                ('meV2sa', models.PositiveIntegerField(default=0, editable=False)),
                ('Ay7vlW', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MfyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('A3EIK9', models.PositiveIntegerField(verbose_name='sector number')),
                ('OJkwnh', models.CharField(max_length=50, verbose_name='mfy name')),
                ('nmTCop', models.PositiveIntegerField(default=0, editable=False)),
                ('KFA1gv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadmin.districtmodel')),
                ('YAWyKM', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
