# Generated by Django 5.0 on 2024-01-11 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districtmodel',
            name='v8yOf2',
        ),
    ]
